apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    name: django
    instance: django-inst
    version: "1.0.0"
    component: server
    part-of: django
spec:
  replicas: 3
  selector:
    matchLabels:
      name: DjangoApp 
  template:
    metadata:
      labels:
        name: DjangoApp
    spec:
      containers:
      - name: djangoapp
        image: django_app
        envFrom:
          - configMapRef:
              name: django-config
        imagePullPolicy: Never
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    name: DjangoApp 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
